### PR TITLE
fix: solve transparency troubles

### PR DESCRIPTION
**Pull request by vincowl**
solves  #28

### CODE REVIEW

**Review by NTBBloodbath — APPROVED** [review]
Thank you so much! :) 💜

**Comment by vincowl** [comment]
My pleasure 😅

**Comment by quarkquartet** [comment]
Is this fixed? I tried to install it on lazyvim via the following:
```
return {

  {
    "NTBBloodbath/doom-one.nvim",
    opts = {
      transparent = true,
      styles = {
        sidebars = "transparent",
        float = "transparent",
      },
    },
  },

  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "doom-one",
    },
  },
}
```

And the transparency did not work.

The error I saw is:
image

My above code has no problem for all other themes that I tried.

**Comment by NTBBloodbath** [comment]
@quarkquartet `doom-one.nvim` is using `vim.g.doom_one_` variables instead of a `setup` function, so installing it with `opts` in your `lazy.nvim` plugin declaration.

**Pull request merged**
